[project]
name = "video2text"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "av>=17.1.0",
    "imageio>=2.37.3",
    "imageio-ffmpeg>=0.6.0",
    "opencv-python-headless>=4.13.0.92",
    "pydantic>=2.0.0",
    "python-dotenv>=1.2.2",
    "scipy>=1.18.0rc1",
    "soundfile>=0.14.0",
    "transformers",
    "vllm",
]

[project.optional-dependencies]
audio = ["vllm[audio]"]

[tool.uv]
environments = ["sys_platform == 'linux'"]
index-strategy = "unsafe-best-match"
prerelease = "allow"

[[tool.uv.index]]
name = "pytorch-cu129"
url = "https://download.pytorch.org/whl/cu129"

[[tool.uv.index]]
name = "vllm-nightly"
url = "https://wheels.vllm.ai/nightly/cu129"

[tool.uv.sources]
vllm = { index = "vllm-nightly" }
