sam_audio:
  model_name: "facebook/sam-audio-small"
  device: "cuda:2"
  alloc_conf: "max_split_size_mb:512"

vad:
  threshold: 0.5
  min_silence_duration_ms: 300
  chunk_seconds: 300.0

asr:
  model: "MediaTek-Research/Breeze-ASR-26"
  batch_size: 64
  language: "zh"

video_desc:
  fps: 1.0
  max_tokens: 24576
  temperature: 1.0

clean:
  chunk_size: 20
  temperature: 1.0

summarize:
  max_tokens: 24576
  temperature: 1.0
  top_p: 0.95